force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <description>Voting for the Employee of the Year nomination</description>
    <label>Vote</label>
    <nameField>
        <displayFormat>Vote-{0}</displayFormat>
        <label>VoteId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Voter__c.field-meta.xml
<CustomField>
    <fullName>Voter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who voted</description>
    <label>Voter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VoteTriggerHandler.cls
public class VoteTriggerHandler extends TriggerHandler {
    private List<Vote__c> newVotes;
    private List<Vote__c> oldVotes;
       
            public VoteTriggerHandler() { 
                this.newVotes = Trigger.New;
                this.oldVotes = Trigger.Old;
           } 
       
           public override void beforeUpdate() {
       
           } 
       
           public override void  beforeInsert () {
               Contact contact = [SELECT Id
                FROM Contact 
                WHERE Active__c = true ];
                
               List<Vote__c> votes = [
                   SELECT Id
                   FROM Vote__c 
                   WHERE Voter__c = :contact.Id];
               
               if (votes.size()>0) {
                for(Vote__c vote : votes) {
                    vote.addError('Your vote was not registered! You have already voted for somebody else!');
                }
               }
           } 
       
           public override void  beforeDelete () {
               //Do magic 
           } 
           public override void  afterInsert () {
       
               //Do magic 
           } 
           public override void afterUpdate() {
                
           } 
           public override void  afterDelete () {
               //Do magic 
           }  
           public override void   afterUndelete  () {
               //Do magic 
           }
       }