force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/VotesTotal__c.field-meta.xml
<CustomField>
    <fullName>VotesTotal__c</fullName>
    <description>Total number of Votes</description>
    <label>VotesTotal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <description>Voting for the Employee of the Year nomination</description>
    <label>Vote</label>
    <nameField>
        <displayFormat>Vote-{0}</displayFormat>
        <label>VoteId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/VoteFor__c.field-meta.xml
<CustomField>
    <fullName>VoteFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For whom vote was given</description>
    <label>VoteFor</label>
    <referenceTo>CandidateInNomination__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voter__c.field-meta.xml
<CustomField>
    <fullName>Voter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who voted</description>
    <label>Voter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/VoteTriggerHandler.cls
public class VoteTriggerHandler extends TriggerHandler {
    private List<Vote__c> newVotes;
    private List<Vote__c> oldVotes;
       
            public VoteTriggerHandler() { 
                this.newVotes = Trigger.New;
                this.oldVotes = Trigger.Old;
           } 
       
           public override void beforeUpdate() {
       
           } 
       
           public override void  beforeInsert () {
                Contact contact = [SELECT Id
                FROM Contact 
                WHERE Active__c = true ];
                
               List<Vote__c> votes = [SELECT Id
                   FROM Vote__c 
                   WHERE Voter__c = :contact.Id];
               
               if (votes.size()>0) {
                    for(Vote__c vote : votes) {
                        vote.addError(new DmlException('Your vote was not registered! You have already voted for somebody else!'));
                        
                    }
               }          
           } 
       
           public override void  beforeDelete () {
               //Do magic 
           } 

           public override void  afterInsert () {
             Vote__c vote = newVotes.get(0);  
             CandidateInNomination__c candidate = [SELECT Id, VotesTotal__c
                FROM CandidateInNomination__c
                WHERE Id = :vote.VoteFor__c];   
             candidate.VotesTotal__c++;
             update candidate;       
          }
        
           public override void afterUpdate() {
                
           } 
           public override void  afterDelete () {
               //Do magic 
           }  
           public override void   afterUndelete  () {
               //Do magic 
           }
       }