force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/CandidateContact__c.field-meta.xml
<CustomField>
    <fullName>CandidateContact__c</fullName>
    <label>CandidateContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations (CandidateContact)</relationshipLabel>
    <relationshipName>CandidatesInNominations1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Nomination__c.field-meta.xml
<CustomField>
    <fullName>Nomination__c</fullName>
    <label>Nomination</label>
    <referenceTo>Nomination__c</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/PushedBy__c.field-meta.xml
<CustomField>
    <fullName>PushedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PushedBy</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for the Candidate to be pushed in a Nomination</description>
    <label>Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Nominations for EOY process. Nominations are created by Advanced User</description>
    <label>Nomination</label>
    <nameField>
        <label>NominationName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomination__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Which Campaign year this nomination relates to</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Nominations</relationshipLabel>
    <relationshipName>Nominations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestCanInNomTrigger.cls
@isTest(SeeAllData=true)
private class TestCanInNomTrigger {
    @isTest static void TestInsertFreshNewCandidate() {
        // Test inserting fresh candidate on fresh pushing contact
        
        //Ensure that the contact has never pushed any candidate yet
        Contact testContact = [SELECT Id 
        FROM Contact 
        WHERE Id NOT IN 
        (SELECT PushedBy__c 
        FROM CandidateInNomination__c)].get(0);

        //Selecting actual campaign for test purposes
        Nomination__c testNomination = [SELECT Id
        FROM Nomination__c 
        WHERE Campaign__c IN 
        (SELECT Id 
        FROM Campaign 
        WHERE Name = 'COV Season 2')].get(0);
        
        //Filling in test data
         CandidateInNomination__c testCandidate = new CandidateInNomination__c();
         testCandidate.Name = 'Test Candidate';
         testCandidate.CandidateContact__c = testContact.Id;
         testCandidate.PushedBy__c = testContact.Id;
         testCandidate.Nomination__c = testNomination.Id;
         testCandidate.Reason__c = 'Test Reason';

        //Perform test
        Test.startTest();
        insert testCandidate;      
        Test.stopTest();

        //Assertion
        CandidateInNomination__c assertCandidate = [SELECT Id, Name
        FROM CandidateInNomination__c
        WHERE Name = :testCandidate.Name].get(0);
    
        System.assertEquals(testCandidate.Name, assertCandidate.Name);
     }

     @isTest TestInsertingFourthCandidate() {

     }
    
}