force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/CandidateContact__c.field-meta.xml
<CustomField>
    <fullName>CandidateContact__c</fullName>
    <label>CandidateContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations (CandidateContact)</relationshipLabel>
    <relationshipName>CandidatesInNominations1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Nomination__c.field-meta.xml
<CustomField>
    <fullName>Nomination__c</fullName>
    <label>Nomination</label>
    <referenceTo>Nomination__c</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/PushedBy__c.field-meta.xml
<CustomField>
    <fullName>PushedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PushedBy</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for the Candidate to be pushed in a Nomination</description>
    <label>Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Nominations for EOY process. Nominations are created by Advanced User</description>
    <label>Nomination</label>
    <nameField>
        <label>NominationName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomination__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Which Campaign year this nomination relates to</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Nominations</relationshipLabel>
    <relationshipName>Nominations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/tests/CandidateControllerTest.cls
@isTest
private class CandidateControllerTest {
	private static final Integer CONTACTS_NUMBER = 20;
	private static final Integer NOMINATIONS_NUMBER = 5;
    private static final Integer CANDIDATES_NUMBER = 5;
	@testSetup
	static void makeData() {
		List<Contact> testContacts = CandidateInNominationTestFactory.createContacts(CONTACTS_NUMBER);
		List<Nomination__c> testNominations = CandidateInNominationTestFactory.createNominationsWithCampaign(
			NOMINATIONS_NUMBER
		);
	}

    @isTest
	static void testGettingApprovedCandidates() {
        Contact activeContact = getActiveContact();

        Nomination__c activeNomination = getActiveNomination();

        List<CandidateInNomination__c> candidates = new List<CandidateInNomination__c>();
        for (Integer i = 0; i < CANDIDATES_NUMBER; i++) {
            CandidateInNomination__c candidate = new CandidateInNomination__c();
		    candidate.Name = 'TestCandidate' + i;
		    candidate.CandidateContact__c = activeContact.Id;
		    candidate.Nomination__c = activeNomination.Id;
		    candidate.PushedBy__c = candidate.CandidateContact__c;
		    candidate.Reason__c = 'TestReason' + i;  
            candidate.Approved__c = true;
            candidates.add(candidate);
        }

        insert candidates;

        List<CandidateInNomination__c> testCandidates = CandidateController.getCandidates();

        System.assertEquals(testCandidates.size(), candidates.size());
    }

    @isTest
	static void testPutVote() {
        Contact activeContact = getActiveContact();

        Nomination__c activeNomination = getActiveNomination();

        List<CandidateInNomination__c> candidates = new List<CandidateInNomination__c>();
        for (Integer i = 0; i < CANDIDATES_NUMBER; i++) {
            CandidateInNomination__c candidate = new CandidateInNomination__c();
		    candidate.Name = 'TestCandidate' + i;
		    candidate.CandidateContact__c = activeContact.Id;
		    candidate.Nomination__c = activeNomination.Id;
		    candidate.PushedBy__c = candidate.CandidateContact__c;
		    candidate.Reason__c = 'TestReason' + i;  
            candidate.Approved__c = true;
            candidates.add(candidate);
        }

        insert candidates;

        List<CandidateInNomination__c> testCandidates = CandidateController.getCandidates();

        System.assertEquals(testCandidates.size(), candidates.size());
    }


    private static Contact getActiveContact() {
		return [SELECT Id, FirstName, LastName FROM Contact WHERE Active__c = TRUE LIMIT 1];
	}

    private static Nomination__c getActiveNomination() {
		return [SELECT Id FROM Nomination__c WHERE Campaign__r.IsActive = TRUE LIMIT 1];
	}
}