force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/CandidateContact__c.field-meta.xml
<CustomField>
    <fullName>CandidateContact__c</fullName>
    <label>CandidateContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations (CandidateContact)</relationshipLabel>
    <relationshipName>CandidatesInNominations1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Nomination__c.field-meta.xml
<CustomField>
    <fullName>Nomination__c</fullName>
    <label>Nomination</label>
    <referenceTo>Nomination__c</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/PushedBy__c.field-meta.xml
<CustomField>
    <fullName>PushedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PushedBy</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for the Candidate to be pushed in a Nomination</description>
    <label>Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Nominations for EOY process. Nominations are created by Advanced User</description>
    <label>Nomination</label>
    <nameField>
        <label>NominationName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomination__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Which Campaign year this nomination relates to</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Nominations</relationshipLabel>
    <relationshipName>Nominations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <description>Voting for the Employee of the Year nomination</description>
    <label>Vote</label>
    <nameField>
        <displayFormat>Vote-{0}</displayFormat>
        <label>VoteId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/VoteFor__c.field-meta.xml
<CustomField>
    <fullName>VoteFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For whom vote was given</description>
    <label>VoteFor</label>
    <referenceTo>CandidateInNomination__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voter__c.field-meta.xml
<CustomField>
    <fullName>Voter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who voted</description>
    <label>Voter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/tests/VoteTHTest.cls
@isTest
private class VoteTHTest {
	private static final Integer CONTACTS_NUMBER = 20;
	private static final Integer NOMINATIONS_NUMBER = 5;
	private static final Integer CANDIDATES_NUMBER = 2;
	@testSetup
	static void makeData() {
		List<Contact> testContacts = CandidateInNominationTestFactory.createContacts(CONTACTS_NUMBER);
		List<Nomination__c> testNominations = CandidateInNominationTestFactory.createNominationsWithCampaign(
			NOMINATIONS_NUMBER
		);
	}

	@isTest
	static void TestAddFreshVote() {
		Contact activeContact = getActiveContact();

		Nomination__c testNomination = getActiveNomination();

		CandidateInNomination__c testCandidate = new CandidateInNomination__c();
		testCandidate.Name = 'TestCandidate';
		testCandidate.CandidateContact__c = activeContact.Id;
		testCandidate.Nomination__c = testNomination.Id;
		testCandidate.PushedBy__c = testCandidate.CandidateContact__c;
		testCandidate.Reason__c = 'TestReason';

		insert testCandidate;

		List<Vote__c> assertVotesBefore = getAllVotes();
		System.assert(assertVotesBefore.size() == 0);

		Vote__c testVote = new Vote__c();
		testVote.Voter__c = activeContact.Id;
		testVote.VoteFor__c = testCandidate.Id;

		//Perform test
		Test.startTest();
		Database.SaveResult result = Database.insert(testVote, false);
		Test.stopTest();

		//Assertion

		System.assert(result.isSuccess());

		List<Vote__c> assertVotesAfter = getAllVotes();

		System.assert(assertVotesAfter.size() == 1);
	}

	@isTest
	static void TestAddDuplicateVote() {
		Contact activeContact = getActiveContact();

		Nomination__c testNomination = getActiveNomination();

		CandidateInNomination__c testCandidate = new CandidateInNomination__c();
		testCandidate.Name = 'TestCandidate';
		testCandidate.CandidateContact__c = activeContact.Id;
		testCandidate.Nomination__c = testNomination.Id;
		testCandidate.PushedBy__c = testCandidate.CandidateContact__c;
		testCandidate.Reason__c = 'TestReason';
	
		insert testCandidate;
		
		Vote__c testVote1 = new Vote__c();
		testVote1.Voter__c = activeContact.Id;
		testVote1.VoteFor__c = testCandidate.Id;

		List<Vote__c> assertVotes1Before = getAllVotes();
		System.assert(assertVotes1Before.size() == 0);

		insert testVote1;

		List<Vote__c> assertVotes1After = getAllVotes();
		System.assert(assertVotes1After.size() == 1);

		Vote__c testVote2 = new Vote__c();
		testVote2.Voter__c = activeContact.Id;
		testVote2.VoteFor__c = testCandidate.Id;

		List<Vote__c> assertVotes2Before = getAllVotes();
		System.assert(assertVotes2Before.size() == 1);
		//Perform test
		Test.startTest();
		Database.SaveResult result = Database.insert(testVote2, false);
		Test.stopTest();

		List<Vote__c> assertVotes2After = getAllVotes();
		System.assert(assertVotes2After.size() == 2);
	}

	private static Contact getActiveContact() {
		return [SELECT Id, FirstName, LastName FROM Contact WHERE Active__c = TRUE LIMIT 1];
	}

	private static Nomination__c getActiveNomination() {
		return [SELECT Id FROM Nomination__c WHERE Campaign__r.IsActive = TRUE LIMIT 1];
	}

	private static List<Vote__c> getAllVotes() {
		return [SELECT Id FROM Vote__c];
	}
}