force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/CandidateContact__c.field-meta.xml
<CustomField>
    <fullName>CandidateContact__c</fullName>
    <label>CandidateContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations (CandidateContact)</relationshipLabel>
    <relationshipName>CandidatesInNominations1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Nomination__c.field-meta.xml
<CustomField>
    <fullName>Nomination__c</fullName>
    <label>Nomination</label>
    <referenceTo>Nomination__c</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for the Candidate to be pushed in a Nomination</description>
    <label>Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/VotesTotal__c.field-meta.xml
<CustomField>
    <fullName>VotesTotal__c</fullName>
    <description>Total number of Votes</description>
    <label>VotesTotal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Nominations for EOY process. Nominations are created by Advanced User</description>
    <label>Nomination</label>
    <nameField>
        <label>NominationName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <description>Voting for the Employee of the Year nomination</description>
    <label>Vote</label>
    <nameField>
        <displayFormat>Vote-{0}</displayFormat>
        <label>VoteId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/VoteFor__c.field-meta.xml
<CustomField>
    <fullName>VoteFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For whom vote was given</description>
    <label>VoteFor</label>
    <referenceTo>CandidateInNomination__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voter__c.field-meta.xml
<CustomField>
    <fullName>Voter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who voted</description>
    <label>Voter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/CandidateController.cls
public inherited sharing class CandidateController {
	@AuraEnabled(cacheable=true)
	public static List<CandidateInNomination__c> getCandidates() {
		return getApprovedCandidates();
	}

	@AuraEnabled
	public static String putVote(String contactToVoteForId) {
		Contact contact = getActiveContact();
		Vote__c vote = new Vote__c();
		vote.Voter__c = contact.Id;
		vote.VoteFor__c = contactToVoteForId;
		try {
			insert vote;
		} catch (Exception e) { 
			throw new AuraHandledException(
				  contact.FirstName + 
				  ' ' +
				  contact.LastName +
				 '!! ' + ' Your vote was not registered as you have voted already!'
			);
		}
		String result = contact.FirstName + ' ' + contact.LastName;
		return result;
	}

	private static List<CandidateInNomination__c> getApprovedCandidates() {
		return [
			SELECT
				Name,
				Nomination__r.Name,
				CandidateContact__r.FirstName,
				CandidateContact__r.LastName,
				CandidateContact__r.Department,
				Reason__c,
				VotesTotal__c
			FROM CandidateInNomination__c
			WHERE Approved__c = TRUE
			ORDER BY Name
		];
	}

	private static Contact getActiveContact() {
		return [SELECT Id, FirstName, LastName FROM Contact WHERE Active__c = TRUE LIMIT 1];
	}
}