force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/Nomination__c.field-meta.xml
<CustomField>
    <fullName>Nomination__c</fullName>
    <label>Nomination</label>
    <referenceTo>Nomination__c</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/PushedBy__c.field-meta.xml
<CustomField>
    <fullName>PushedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PushedBy</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CandidateInNomination__c/fields/VotesTotal__c.field-meta.xml
<CustomField>
    <fullName>VotesTotal__c</fullName>
    <description>Total number of Votes</description>
    <label>VotesTotal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Nominations for EOY process. Nominations are created by Advanced User</description>
    <label>Nomination</label>
    <nameField>
        <label>NominationName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <description>Voting for the Employee of the Year nomination</description>
    <label>Vote</label>
    <nameField>
        <displayFormat>Vote-{0}</displayFormat>
        <label>VoteId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/VoteFor__c.field-meta.xml
<CustomField>
    <fullName>VoteFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For whom vote was given</description>
    <label>VoteFor</label>
    <referenceTo>CandidateInNomination__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/CandidateInNominationTH.cls
public class CandidateInNominationTH extends TriggerHandler {
	private List<CandidateInNomination__c> newCandidates;
	private List<CandidateInNomination__c> oldCandidates;
	public static final Integer MAX_CANDIDATES = 2;

	public CandidateInNominationTH() {
		this.newCandidates = Trigger.new;
		this.oldCandidates = Trigger.old;
	}

	public override void beforeUpdate() {
	}

	public override void beforeInsert() {
		Contact contact = getActiveContact();

		CandidateInNomination__c candidateCheck = newCandidates.get(0);
		List<CandidateInNomination__c> candidateChecklist = [
			SELECT Id
			FROM CandidateInNomination__c
			WHERE PushedBy__c = :contact.Id
			AND Nomination__c = :candidateCheck.Nomination__c
		];

		if (candidateChecklist.size() > MAX_CANDIDATES) {
			for (CandidateInNomination__c candidate : newCandidates) {
				candidate.addError('Cannot add Candidate in this nomination! Already 3 candidates from this user!');
			}
		} else {
			for (CandidateInNomination__c candidate : newCandidates) {
				candidate.PushedBy__c = contact.Id;
				candidate.VotesTotal__c = 0;
			}
		}
	}

	public override void beforeDelete() {
		List<Vote__c> votes = [SELECT Id FROM Vote__c WHERE VoteFor__c IN :oldCandidates]; //safer to enwrap in new List<Vote__c>
		if (!votes.isEmpty())
			delete votes;
	}
	public override void afterInsert() {
		//Do magic
	}
	public override void afterUpdate() {
	}
	public override void afterDelete() {
	}

	public override void afterUndelete() {
		//Do magic
	}

	private static Contact getActiveContact(){
		return [SELECT Id FROM Contact WHERE Active__c = TRUE LIMIT 1];
	}
}