force-app/main/default/objects/CandidateInNomination__c/CandidateInNomination__c.object-meta.xml
<CustomObject>
    <description>Junction Table for Many-to-Many Candidate-Nomination relations</description>
    <label>CandidateInNomination</label>
    <nameField>
        <label>CandidateInNomination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesInNominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CandidateInNomination__c/fields/PushedBy__c.field-meta.xml
<CustomField>
    <fullName>PushedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PushedBy</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CandidatesInNominations</relationshipLabel>
    <relationshipName>CandidatesInNominations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CanInNomTriggerHandler.cls
public class CanInNomTriggerHandler extends TriggerHandler {
    // private List<CandidateInNomination__c> newCandidates;
    // private List<CandidateInNomination__c> oldCandidates;

    public CanInNomTriggerHandler() { 
        // newCandidates = new List<CandidateInNomination__c>();
        // oldCandidates = new List<CandidateInNomination__c>();
    } 

    public override void beforeUpdate() {

    } 

    public override void  beforeInsert () {
        Contact contact = [SELECT Id
         FROM Contact 
         WHERE Active__c = true ];

         for(CandidateInNomination__c candidate : Trigger.New) {
            candidate.PushedBy__c = contact.Id;
         }
    } 

    public override void  beforeDelete () {
        //Do magic 
    } 
    public override void  afterInsert () {
        // Contact contact = [SELECT Id
        // FROM Contact 
        // WHERE Active__c = true ];
        // CandidateInNomination__c candidate = [SELECT Id, PushedBy__c
        // FROM CandidateInNomination__c WHERE
        // Id = :Trigger.New];

        // candidate.PushedBy__c = contact.Id;

        // update candidate;

        //Do magic 
    } 
    public override void afterUpdate() {
        // Contact contact = [SELECT Id
        // FROM Contact 
        // WHERE Active__c = true ];
        // CandidateInNomination__c candidate = [SELECT Id, PushedBy__c
        // FROM CandidateInNomination__c WHERE
        // Id = :Trigger.New];

        // candidate.PushedBy__c = contact.Id;

        // update candidate;

         
    } 
    public override void  afterDelete () {
        //Do magic 
    }  
    public override void   afterUndelete  () {
        //Do magic 
    }
}