force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Nominations for EOY process. Nominations are created by Advanced User</description>
    <label>Nomination</label>
    <nameField>
        <label>NominationName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomination__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Which Campaign year this nomination relates to</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Nominations</relationshipLabel>
    <relationshipName>Nominations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/tests/CandidateInNominationTestFactory.cls
@isTest
public class CandidateInNominationTestFactory {
    public static List<Contact> createContacts(Integer contactsNumber) {
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i< contactsNumber-1; i++) {
            Contact newContact = new Contact();
            newContact.FirstName = 'TestName'+i;
            newContact.LastName = 'TestName'+i;
            newContact.Active__c = false;
            contacts.add(newContact);
        }
        Contact activeContact = new Contact();
        activeContact.FirstName = 'Active';
        activeContact.LastName = 'Contact';
        activeContact.Active__c = true;
        contacts.add(activeContact);

        insert contacts;

        return contacts;
    }

    public static List<Nomination__c> createNominationsWithCampaign(Integer nominationsNumber) {
        Campaign runningCampaign = new Campaign();
        runningCampaign.IsActive = true;
        runningCampaign.Name = 'TestCampaign';
        insert runningCampaign;

        List<Nomination__c> nominations = new List<Nomination__c>();
        for (Integer i = 0; i< nominationsNumber; i++) {
            Nomination__c newNomination = new Nomination__c();
            newNomination.Name = 'TestNomination'+i;
            newNomination.Campaign__c = runningCampaign.Id;
            nominations.add(newNomination);
        }

        insert nominations; 
        return nominations;
    }
}